/**
 * Regras centrais usadas pela engine.
 */
module.exports = {
  MIN_PLAYERS: 2,
  MAX_PLAYERS: 4,
  START_HP: 3000,
  CARDS_PER_TURN_DRAW: 1,
  MAX_CHARACTERS_FIELD: 5,
  MAX_MAGIC_FIELD: 5,
  CHARACTER_SUMMONS_PER_TURN: 1,
  MAGIC_ACTIVATIONS_PER_TURN: 1,
  BOSS_SPAWN_EVERY_ROUNDS: 3,
  XP_PER_LEVEL: 300,
  REWARDS: {
    BOSS_DEFEAT_ALL: 40,
    ELIMINATION_ALL_EXCEPT_DEFEATED: 40,
    TOP_BOSS_DAMAGE: 100,
    LOSE_MATCH: 20,
    WIN_MATCH: 150
  }
};
